import { useCallback, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toPng } from 'html-to-image'

import { useSimulationStore } from '../../stores/simulation'
import { useRelationshipsStore } from '../../stores/relationships'

function watermarkText(time: string, tick: number): string {
  return `POPULACE | ${time} | Tick ${tick}`
}

function triggerDownload(dataUrl: string, filename: string) {
  const link = document.createElement('a')
  link.download = filename
  link.href = dataUrl
  link.click()
}

async function captureMapScreenshot(time: string, tick: number): Promise<string> {
  const mapRegion = document.querySelector('[role="region"][aria-label]') as HTMLElement | null
  if (!mapRegion) throw new Error('Map region not found')

  const dataUrl = await toPng(mapRegion, {
    cacheBust: true,
    pixelRatio: 2,
    filter: (node) => {
      // Skip hidden elements and context menus
      if (node instanceof HTMLElement && node.dataset.townContextMenu) return false
      return true
    },
  })

  // Add watermark
  const img = new Image()
  img.src = dataUrl
  await new Promise<void>((resolve) => { img.onload = () => resolve() })

  const canvas = document.createElement('canvas')
  canvas.width = img.width
  canvas.height = img.height
  const ctx = canvas.getContext('2d')!
  ctx.drawImage(img, 0, 0)

  // Watermark bar
  const barHeight = 36
  ctx.fillStyle = 'rgba(2, 6, 23, 0.75)'
  ctx.fillRect(0, canvas.height - barHeight, canvas.width, barHeight)
  ctx.font = 'bold 14px "Avenir Next", "Helvetica Neue", sans-serif'
  ctx.fillStyle = 'rgba(226, 232, 240, 0.8)'
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'
  ctx.fillText(watermarkText(time, tick), canvas.width / 2, canvas.height - barHeight / 2)

  return canvas.toDataURL('image/png')
}

function generateShareCard(
  time: string,
  tick: number,
  residentCount: number,
  relationshipCount: number,
  highlights: string[],
): string {
  const width = 600
  const height = 400
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')!

  // Background gradient
  const grad = ctx.createLinearGradient(0, 0, width, height)
  grad.addColorStop(0, '#0f172a')
  grad.addColorStop(1, '#020617')
  ctx.fillStyle = grad
  ctx.fillRect(0, 0, width, height)

  // Dot grid overlay
  ctx.fillStyle = 'rgba(148, 163, 184, 0.06)'
  for (let x = 0; x < width; x += 16) {
    for (let y = 0; y < height; y += 16) {
      ctx.beginPath()
      ctx.arc(x + 8, y + 8, 0.8, 0, Math.PI * 2)
      ctx.fill()
    }
  }

  // Title
  ctx.fillStyle = '#e2e8f0'
  ctx.font = 'bold 32px "Avenir Next", "Helvetica Neue", sans-serif'
  ctx.textAlign = 'center'
  ctx.fillText('POPULACE', width / 2, 56)

  // Subtitle
  ctx.fillStyle = '#94a3b8'
  ctx.font = '14px "Avenir Next", "Helvetica Neue", sans-serif'
  ctx.fillText(`${time} | Tick ${tick}`, width / 2, 84)

  // Stats row
  const stats = [
    { label: '\u{1F464} \u5C45\u6C11', value: String(residentCount) },
    { label: '\u{1F91D} \u5173\u7CFB', value: String(relationshipCount) },
  ]

  const statsY = 140
  const statsSpacing = 160
  const statsStartX = (width - statsSpacing * (stats.length - 1)) / 2

  stats.forEach((stat, i) => {
    const x = statsStartX + i * statsSpacing
    // Value
    ctx.fillStyle = '#3b82f6'
    ctx.font = 'bold 42px "Avenir Next", "Helvetica Neue", sans-serif'
    ctx.textAlign = 'center'
    ctx.fillText(stat.value, x, statsY)
    // Label
    ctx.fillStyle = '#64748b'
    ctx.font = '13px "Avenir Next", "Helvetica Neue", sans-serif'
    ctx.fillText(stat.label, x, statsY + 24)
  })

  // Highlights
  if (highlights.length > 0) {
    ctx.fillStyle = '#475569'
    ctx.font = '11px "Avenir Next", "Helvetica Neue", sans-serif'
    ctx.textAlign = 'center'
    ctx.fillText('\u2014 \u4EAE\u70B9\u4E8B\u4EF6 \u2014', width / 2, 210)

    ctx.fillStyle = '#cbd5e1'
    ctx.font = '14px "Avenir Next", "Helvetica Neue", sans-serif'
    ctx.textAlign = 'center'
    highlights.slice(0, 4).forEach((h, i) => {
      const text = h.length > 50 ? h.slice(0, 47) + '\u2026' : h
      ctx.fillText(text, width / 2, 240 + i * 28)
    })
  }

  // Footer
  ctx.fillStyle = '#334155'
  ctx.font = '11px "Avenir Next", "Helvetica Neue", sans-serif'
  ctx.textAlign = 'center'
  ctx.fillText('Generated by Populace Simulation', width / 2, height - 20)

  return canvas.toDataURL('image/png')
}

export function ScreenshotButton() {
  const { t } = useTranslation()
  const [busy, setBusy] = useState(false)
  const time = useSimulationStore((s) => s.time)
  const tick = useSimulationStore((s) => s.tick)

  const handleScreenshot = useCallback(async () => {
    if (busy) return
    setBusy(true)
    try {
      const dataUrl = await captureMapScreenshot(time, tick)
      triggerDownload(dataUrl, `populace-${tick}.png`)
    } catch {
      // Silently fail
    } finally {
      setBusy(false)
    }
  }, [busy, time, tick])

  return (
    <button
      type="button"
      onClick={() => void handleScreenshot()}
      disabled={busy}
      className="btn-micro flex h-6 w-6 items-center justify-center rounded-full border border-white/15 bg-white/5 text-[11px] text-slate-300 transition duration-200 hover:bg-white/10 hover:text-white active:scale-95 disabled:opacity-40"
      title={t('screenshot.capture', '\u622A\u56FE')}
      aria-label={t('screenshot.capture', '\u622A\u56FE')}
      data-testid="screenshot-button"
    >
      {busy ? '\u23F3' : '\u{1F4F7}'}
    </button>
  )
}

export function ShareCardButton() {
  const { t } = useTranslation()
  const [busy, setBusy] = useState(false)
  const time = useSimulationStore((s) => s.time)
  const tick = useSimulationStore((s) => s.tick)
  const residents = useSimulationStore((s) => s.residents)
  const relationships = useRelationshipsStore((s) => s.relationships)
  const messageFeed = useSimulationStore((s) => s.messageFeed)

  const handleShare = useCallback(() => {
    if (busy) return
    setBusy(true)
    try {
      const highlights = messageFeed
        .filter((m) => m.kind === 'event')
        .slice(-4)
        .map((m) => m.text)

      const dataUrl = generateShareCard(
        time,
        tick,
        residents.length,
        relationships.length,
        highlights,
      )
      triggerDownload(dataUrl, `populace-card-${tick}.png`)
    } finally {
      setBusy(false)
    }
  }, [busy, time, tick, residents.length, relationships.length, messageFeed])

  return (
    <button
      type="button"
      onClick={handleShare}
      disabled={busy}
      className="btn-micro flex h-6 w-6 items-center justify-center rounded-full border border-white/15 bg-white/5 text-[11px] text-slate-300 transition duration-200 hover:bg-white/10 hover:text-white active:scale-95 disabled:opacity-40"
      title={t('screenshot.share_card', '\u5206\u4EAB\u5361\u7247')}
      aria-label={t('screenshot.share_card', '\u5206\u4EAB\u5361\u7247')}
      data-testid="share-card-button"
    >
      {busy ? '\u23F3' : '\u{1F4E4}'}
    </button>
  )
}
